### ISSUE TITLE
data

### ISSUE THREAD

**Issue by Adele0108** [PsiPhiTheta/LSTM-Attention#1]
Could you please share the data folder, thanks~

**Comment by PsiPhiTheta** [comment]
Please see the docstrings 

```
See https://www.kaggle.com/c/two-sigma-financial-news/data for full 
        description of the dataframe.
```

**Comment by Adele0108** [comment]
Thank you very much for your reply. But there's something wrong with this Kaggle competition, and the data can't be downloaded. Could you please share the original data, thanks!

**Comment by PsiPhiTheta** [comment]
I believe that's intentional by Kaggle to avoid people using the data outside their platform and is the same reason the data is not included in this repo

**Comment by Adele0108** [comment]
Could you please send the data to my email adelesmile@163.com? I'm doing some research on time series forecasting, and your code can help me a lot. Pardon the bother, and many thanks for your kindness.
